services:
  llamacpp:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    privileged: false
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics